
## Exercise: Set up a project on GitHub

[Go here for the video tutorial version of this exercise](https://www.youtube.com/watch?v=PPbESwm6xcA).

Now that we understand how useful GitHub is for creating reproducible analyses, it's time to set ourselves up on GitHub.

Git and GitHub have a whole rich world of tools and terms that can get complex quickly, but for this exercise, we will not worry about those terms and functionalities just yet, but focus on getting code up on GitHub so we are ready to collaborate and conduct open analyses!

- Go to <a href="https://github.com/" target="_blank">Github's main page</a> and click Sign Up if you don't have an account.
- Follow <a href="https://docs.github.com/en/get-started/quickstart/create-a-repo" target="_blank">these instructions to create a repository</a>. As a general, but not absolute rule, you will want to keep one GitHub repository for one analysis project.
  - Name the repository something that reminds you what its related to.
  - Choose `Public`.
  - Check the box that says `Add a README`.
- Follow <a href="https://docs.github.com/en/repositories/working-with-files/managing-files/adding-a-file-to-a-repository#adding-a-file-to-a-repository-on-github" target="_blank">these instructions</a> to add the example files you downloaded to your new repository.

Congrats! You've started your very own project on GitHub!
We encourage you to do the same with your own code and other projects!

**Any feedback you have regarding this exercise is greatly appreciated; you can fill out [this form](https://forms.gle/ygSSwoGaEATA2S65A)!**
